### ISSUE TITLE
Is it the NGAC used?

### ISSUE THREAD

**Issue by toop** [lgwillmore/warden#32]
Is it the NGAC used? Execute only the properties in the policy point, rather than reading the property values of users and objects from the database to make judgments, so that there are no performance issues.

**Comment by lgwillmore** [comment]
NGAC looks very interesting, but Warden is not an NGAC implementation. It is ABAC.

But it has components and execution that provide an initial reasonable efficient execution:

 - if you have fetched the user and resource you are checking access for as part of your request, you already have a chunk of the attributes that you would need to check access, and so you can check access after fetching and avoid additional fetches.
 - if there are additional attributes needed by your policies, you can decide how to enrich the attributes of your user or resource with a Policy Informatioin Point. How you do this is up to your implementation. See here https://warden-kotlin.netlify.app/components/#information-point. This can be done in a way that checks if a particular attribute exists in the request before fetching and enriching.
 
 But generally, if your policies require knowledge of attributes of your resource or your user, then at some point there will probably have to be a DB call to fetch those attributes in order to check them. Even in NGAC you would need to do some sort of call to see if a relationship exists in order to decipher attributes and check policies.
